# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoalTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoalTracker

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FSCalendar'
  pod 'QVRWeekView'
  pod 'CalendarKit'
end
